---
- hosts: all
  tasks:
    - name: install apache
      yum: 
        name: httpd
        state: latest
    - name: enable and start service httpd
      systemd:
        name: httpd
        enabled: yes
        state: started
    - name: permit http traffic through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled