---
- hosts: all
  tasks:
    - name: install apache
      yum: 
        name: httpd
        state: latest
    - name: enable and start service httpd
      systemd:
        name: httpd
        enabled: yes
        state: started
    - name: permit http traffic through the firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
    - name: reload firewalld
      command: firewall-cmd --reload
    - name: Before Ansible 2.3, option 'dest', 'destfile' or 'name' was used instead of 'path'
      replace:
        path: /usr/share/httpd/noindex/index.html.en-US
        regexp: 'Test Page'
        replace: 'Ansible Test Page'