---
- hosts: all
  tasks:
    - name: install apache
      yum: 
        name: httpd
        state: latest
    - name: enable and start service httpd
      systemd:
        name: httpd
        enabled: yes
        state: started