---
- hosts: all
  tasks:
    - name: uninstall apache
      yum: 
        name: httpd
        state: absent
    - name: disable service httpd
      ignore_errors: yes
      systemd:
        name: httpd
        enabled: no
        state: stopped
    - name: block http traffic through the firewall
      firewalld:
        service: http
        permanent: yes
        state: disabled
    - name: reload firewalld
      command: firewall-cmd --reload